### PR TITLE
rows can be sorted by isSelected property

### PR DESCRIPTION
**Pull request by sly7-7**
I'm not sure if it's the right direction, since it is intrusive (it mutate the state of the underlying client item).
An other solution (more difficult to implement) could be to wrap the item in a Row object (maybe an ObjectProxy?), and only delegate to the underlying object when necessary. But it implies a large refactoring, I'm not sure to be capable of.
At least, I need some help to give me the direction

### CODE REVIEW

**Comment by onechiporenko** [comment]
@sly7-7, thanks for PR, however I can't merge it. You try to set property `isSelected` for each row. Firstly, 
changing rows is not allowed, because this data doesn't belongs to `models-table`. Component can only read it. Secondly, property `isSelected` may be already defined in the table-data and used for something else. Thirdly,  it may be read-only.

**Comment by sly7-7** [comment]
@onechiporenko So, how do you think it can be implemented ? Would the following alternative consisting be viable ? 
We could wrap the data item with a `models-table` row object, acting like a proxy on the object, plus having some specific properties (for example the isSelected flag)

**Comment by onechiporenko** [comment]
* Flag `selectedFirst` may be added to the `models-table`. If it's `true` selected items should be first and not selected should be after them.
* `arrangedContent` may be updated to handle `selectedItems` and `selectedFirst`.

**Comment by sly7-7** [comment]
@onechiporenko I've tried to implement what you describe here. Let me now how it goes.

**Pull request closed without merging**
