### PR TITLE
Fixed sorting icons

### PR DESCRIPTION
**Pull request by 1int**
Sorting icons were in the wrong order: v for ASC and /\ for DESC.

### CODE REVIEW

**Comment by 1int** [comment]
hey, any update on this?

**Comment by onechiporenko** [comment]
Sorry for so long delay. Thanks for PR and could you please update it (UT should not fail)?
I mean only test `Integration: updateable columns (disabled)`. Other currently fails for another reasons.

**Comment by josefguenther** [comment]
Any update? Can I help? Why are the builds failing for other reasons?

**Comment by SIRHAMY** [comment]
Actually, I think the icons were correct to begin with and this change would cause it to break. For reference, I'm using the [Common Table](http://onechiporenko.github.io/ember-models-table/#/examples/sort-by) example available from the repo.

Here, we can see that clicking on the ID field causes the list to be sorted in ASC(ending) order, starting at 1 and going to 30. The glyph that appears here is the down chevron.

Clicking again sets the table to be sorted in DESC(ending) order with the element IDs going from 30 to 1. The associated chevron is up.

In my opinion, this is correct - showing the natural taxonomy/ordering from start to finish. There may be cases where things aren't being ordered from the top that I haven't considered, but it seems to me that this would be a breaking change for the given example.

**Comment by alejandrocibilich** [comment]
IMHO, I believe thar the icons should be swapped. ASC(ending) should have the point of the triangle pointing up and the base down (glyphicon-triangle-top), and DESC(ending) should have the point of the triangle pointing down and the base up (glyphicon-triangle-bottom).

**Comment by Caltor** [comment]
@alejandrocibilich I agree. The width of the triangle should match the data.

**Pull request closed without merging**
