### PR TITLE
Fix #128 - provide default values when filteredContent.meta is empty.

### LINKED ISSUE #128: Cannot access property on meta (ModelsTableServerPaginated)
Hey,

I'm just extending the `ModelsTableServerPaginated` to my needs. I realized there is an error, which I fixed in my subclass:

```
    arrangedContentLength: Ember.computed('filteredContent.meta', function () {
      var itemsCountProperty = Ember.get(this, 'metaItemsCountProperty');
      var meta = Ember.get(this, 'filteredContent.meta') || {};
      return Ember.get(meta, itemsCountProperty) || 0;
    }),

    pagesCount: Ember.computed('filteredContent.meta', function () {
      var pagesCountProperty = Ember.get(this, 'metaPagesCountProperty');
      var meta = Ember.get(this, 'filteredContent.meta') || {};
      return Ember.get(meta, pagesCountProperty) || 1;
    })
```

the relevant part is: `var meta = Ember.get(this, 'filteredContent.meta') || {};`, to be precise: `|| {}` needs to be added in case there is no meta. Well, which in my case is existent, yet this fixed it for me.

### PR DESCRIPTION
**Pull request by ruzz311**
I ran into this issue as well when extending models-table-server-paginated but decided to PR the change proposed by @gossi

### CODE REVIEW

**Comment by onechiporenko** [comment]
@ruzz311, as for me, `Serializer` should handle BE-responses with models data and check if `meta` exists

**Comment by ruzz311** [comment]
I'm fairly new to how ember does things but I requested this change to help with various component integration testing.  I've extended the server-pagination component and we have a more complex version that fails on render tests with out us being overly explicit.

Maybe there's a better way since the only time this is a problem for me is in tests; a common DS mock suite perhaps?   Regardless, I do believe handling unexpected inputs in a graceful way with low of effort might make this component stronger.

**Comment by ruzz311** [comment]
@onechiporenko - Really appreciate this merge.  Our app is evolving and I'm sure we'll end up using Mirage like you are for the docs but we just haven't written enough yet.

I'm slowly PR'ing things I've been doing to extend the base functionality of the server-paginated, so if the next few look a little out there or aren't what you want on your roadmap let me know.

**Comment by onechiporenko** [comment]
Ok, @ruzz311. Thank you

**Pull request merged**
