### PR TITLE
Added Public API to programmatically interact with the component

### PR DESCRIPTION
**Pull request by gosenkyl**
Records were edited outside of the component and I needed the ability to refilter the table. The Public API that is being exposed can/will be expanded upon for other things such as reseting the selected rows.

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
Yes, will definitely will be able to expand this and solve a couple other issues listed here.

**Comment by bgantzler** [comment]
I would like you to look at an approve this one as well. Once done can issue another request to add a few more, and that should fix the issues of requests to reset and alter the selected items.

If you are unfamiliar with this its similar to how [ember-power-select](https://github.com/cibernox/ember-power-select) does it.

**Comment by onechiporenko** [comment]
Hi, @gosenkyl. Sorry for such delay with a response. Could you please provide a demo with a described problem (https://ember-twiddle.com)? Normally table-content should be updated when `data` is changed.

**Comment by gosenkyl** [comment]
@onechiporenko The table/data is being updated but the filters are not being reapplied etc.

Here is an example, https://ember-twiddle.com/36bd156cfa64a0ba7057e0745d0c0bff

I have the table filtered by color = red. I change the color to green and even though the rows data changes to green, it should no longer be displayed as I am filtered on red.

**Comment by cah-briangantzler** [comment]
As an added note, we did implement this with it monitoring all the fields and responding accordingly. This however performed poorly on a large set. Since we know we  changed a record and would like it to re-filter, just calling the exposed API was a much better choice.

**Comment by onechiporenko** [comment]
@gosenkyl, @cah-briangantzler, I spend some time googling and found interesting issue in the ember-repo - https://github.com/emberjs/ember.js/issues/10661.
Well, I can't accept a solution with usage component's internal stuff from the outside, however for now I don't know how to keep `filteredContent` updated....
Now for your project you can extend or reopen a `models-table` Component and use your solution, but it has to be a way to "fix" this.

**Comment by gosenkyl** [comment]
One of the best and most popular add-on developers has exposed a few internal methods for this exact reason.

http://ember-power-select.com/docs/api-reference

As mentioned above, I created the filteredContent computed property dynamically based on the columns properties in the didReceiveAttrs and while it worked as expected (refiltered on change of data), it was way too expensive to do that way. With hundreds or thousands of rows, the initial load went from a half of a second to 15 seconds due to computing on every single cell's data.

There comes a point where trying to be too smart and watch for so many moving parts to change becomes too expensive and inefficient. The developer knows when data changed internal to the table, it seems logical to allow a "force refilter". It doesn't give the developer access to "too much of the internals", refiltering the table on demand does very minimal. I would definitely have a problem with exposing other particular functions/fields but this isn't one of them.

This is also necessary for @bgantzler to add built in, in-line table editing as the same problem will occur.

**Comment by cah-briangantzler** [comment]
I guess I should have been more clear.  We did change filtered content to be invalidated on all the correct fields and it performed really poorly on large sets. We un-did that code and went with this approach. This puts the control in the users hands. If the value changes and you do NOT want the table to refilter, dont call this method. Why? Perhaps the user changed something accidentally, an auto filter would have filtered it out and they would have to search to find the record to search. Maybe you want to not filter, leave the record there to change it. If you want it to auto filter, call the exposed method after the record changes. Point is its the user call now.

Sorting should kinda work the same way, some people want it to sort immediately, some dont so the record stays on the screen in the same place and not jarring to the user to disappear. This should be the users call not a mandated thing.

I havent got much time but was working on updating processedColumns to a real computed property   using definedProperty, when its down you'll see what I mean. This approach is ok for because the columns array will have few records. This approach is poor performing for the data (filteredContent), and takes the choice out of the developers hands on when the data is refiltered.

As for your concern, what is exposed is will be public APIs and not much different than functions being yielded. This is the approach that will also solve the questions about access to selected items. For that for example, I would NOT expose the selectedItems array, its a copy half the time and in the future you may choose to internally store it a different way. What would be exposed is a selectedItems.clear, selectedItemc.remove, selectedItems.add, selectedItems.fetch. In this way you are not exposing internals but instead exposing a publicApi that will interact with the internals.

As Kyle mentions, take a look at ember-power-select, this approach is patterned of his component, and we will try to make it as close to his as possible.

Sorry for the long text :) Trying to explain a lot.

**Comment by onechiporenko** [comment]
Well.. Thanks for clarifications. Ok, I'll merge this PR. Fix merge-conflicts, pls.

**Comment by bgantzler** [comment]
The conflicts have been fixed

**Comment by onechiporenko** [comment]
Thanks!

**Pull request merged**
