### PR TITLE
Add placeholder for search input field

### PR DESCRIPTION
**Pull request by Walther**
Something like this could be a nice improvement.
Users can already define the label with `customMessages` and `searchLabel`, and it would be nice to expose the `placeholder` attribute as well.

Feel free to comment about possible additional requirements / if this PR requires any further work.

### CODE REVIEW

**Comment by onechiporenko** [comment]
Hi, @Walther. Thanks for PR!
Could you also add default value (even empty string) to the https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L57 ?

**Comment by Walther** [comment]
Added in d7f87fd

**Comment by onechiporenko** [comment]
Thanks!

**Comment by jameshoward** [comment]
Similar for the filter text boxes would be awesome.

**Pull request merged**
